clientVersion: "dev_0.0.1.0076"
maxCredits: 99999999
generalTime: 420000
preparativeTime: 15000
maxPlayersInRoom: 2
afkTime: 900000
maxPlayers: 100
serverPort: 44839
apiPort: 59483
apiMaxConnections: 10000